# -*- mode: ruby -*-
# vi: set ft=ruby :


RAM = 2048
CPU = 2
IP = "192.168.56.5"
Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.provider "virtualbox" do |v|
    v.memory = RAM
    v.cpus = CPU
  end
  config.vm.network "private_network", ip: IP
end
